## Reshape

In [2]:
import numpy as np

In [4]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [5]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [7]:
a.reshape(3*2)
print(a)

[0 1 2 3 4 5]


In [16]:
np.random.choice(6)

0

In [26]:
b = np.array([[0,0,1],[0,1,0],[1,0,0]])
print(b)
BOARD_COLS = 3
c = np.array([[1,0,0],[0,1,0],[1,0,1]])

[[0 0 1]
 [0 1 0]
 [1 0 0]]


In [28]:
diag_sum1 = sum([b[i, i] for i in range(BOARD_COLS)])
print(diag_sum1)

1


In [24]:
diag_sum2 = sum([b[i, BOARD_COLS - i - 1] for i in range(BOARD_COLS)])
print(diag_sum2)

3
