## Reshape

In [2]:
import numpy as np

In [4]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [5]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [7]:
a.reshape(3*2)
print(a)

[0 1 2 3 4 5]


In [16]:
np.random.choice(6)

0

In [32]:
b = np.array([[0,0,1],[0,1,0],[1,0,0]])
print(b)
BOARD_COLS = 3
c = np.array([[1,0,0],[0,1,0],[1,0,1]])
print(c)

[[0 0 1]
 [0 1 0]
 [1 0 0]]
[[1 0 0]
 [0 1 0]
 [1 0 1]]


In [31]:
diag_sum1 = sum([c[i, i] for i in range(BOARD_COLS)])
print(diag_sum1)

3


In [24]:
diag_sum2 = sum([b[i, BOARD_COLS - i - 1] for i in range(BOARD_COLS)])
print(diag_sum2)

3


In [2]:
if np.random.rand() < 0.5 else -1

SyntaxError: invalid syntax (3625181564.py, line 1)